; User Task Initialization File for GADDS-NT
;
; Format:
; [#]   Starts section for user task number #
; menu="xxx"    ; menubar text inside quotes
; help="xxx"    ; menubar help text inside quotes (optional)
; slam="xxx"    ; slam command inside quotes, without replaceable parms
; parm=type,"xxx","xxx"
;       ...
; parm=type,"xxx","xxx"
;               ; upto ten replaceable parameters with three values
;               ;   type is currently unused, use 0
;               ;   prompt text inside quotes
;               ;   prompt help text inside quotes (optional)

[1]
menu="&Demo loop"
help="Run GADDS verification test procedure"
slam="@GADDS$TEST:gadds"

[2]
menu="&C2_XYZ App Test 15 cm"
help="Collect GADDS corundum application test frames & process"
slam="@GADDS$TEST:c2"
;slam="@GADDS$TEST:c2co"
;slam="@GADDS$TEST:c2cr"
;
;CEC stage on TH-TH base changes are:
;menu="&CEC App Test 15 cm"

[3]
menu="&C2_XYZ Reprocess 15 cm"
help="Update with new distance/beam center and reprocess frames"
slam="@GADDS$TEST:c2_mod"
;slam="@GADDS$TEST:c2_modco"
;slam="@GADDS$TEST:c2_modcr"
;
;CEC stage on TH-TH base changes are:
;menu="&CEC Reprocess 15 cm"

[4]
menu="&C2_XYZ App Test 20 cm"
help="Collect GADDS corundum application test frames & process"
slam="@GADDS$TEST:c2_20cm"
;slam="@GADDS$TEST:c2co_20cm"
;slam="@GADDS$TEST:c2cr_20cm"
;
;CEC stage on TH-TH base changes are:
;menu="&CEC App Test 20 cm"

[5]
menu="&C2_XYZ Reprocess 20 cm"
help="Update with new distance/beam center and reprocess frames"
slam="@GADDS$TEST:c2_mod_20cm"
;slam="@GADDS$TEST:c2_modco_20cm"
;slam="@GADDS$TEST:c2_modcr_20cm"
;
;CEC stage on TH-TH base changes are:
;menu="&CEC Reprocess 20 cm"

[6]
menu="&C2_XYZ App Test 25 cm"
help="Collect GADDS corundum application test frames & process"
slam="@GADDS$TEST:c2_25cm"
;slam="@GADDS$TEST:c2co_25cm"
;slam="@GADDS$TEST:c2cr_25cm"
;
;CEC stage on TH-TH base changes are:
;menu="&CEC App Test 25 cm"

[7]
menu="&C2_XYZ Reprocess 25 cm"
help="Update with new distance/beam center and reprocess frames"
slam="@GADDS$TEST:c2_mod_25cm"
;slam="@GADDS$TEST:c2_modco_25cm"
;slam="@GADDS$TEST:c2_modcr_25cm"
;
;CEC stage on TH-TH base changes are:
;menu="&CEC Reprocess 25 cm"

[8]
menu="&C2_XYZ App Test 30 cm"
help="Collect GADDS corundum application test frames & process"
slam="@GADDS$TEST:c2_30cm"
;slam="@GADDS$TEST:c2co_30cm"
;slam="@GADDS$TEST:c2cr_30cm"
;
;CEC stage on TH-TH base changes are:
;menu="&CEC App Test 30 cm"

[9]
menu="&C2_XYZ Reprocess 30 cm"
help="Update with new distance/beam center and reprocess frames"
slam="@GADDS$TEST:c2_mod_30cm"
;slam="@GADDS$TEST:c2_modco_30cm"
;slam="@GADDS$TEST:c2_modcr_30cm"
;
;CEC stage on TH-TH base changes are:
;menu="&CEC Reprocess 30 cm"

[10]
menu="&Read WANDA XRD plate"
help="Run a plate deposited by WANDA robot"
slam="@C:\robot\scripts\run96wellPlate.slm"
parm=0,"Experiment ID","Enter the basename (jobname) for all filenames"
parm=0,"Scan Time","Enter scan time in seconds per frame"
parm=0,"Title","Enter sample title"
parm=0,"Sample name","Enter sample name / plate ID"
parm=0,"Sample number","Enter sample number"
parm=0,"Number of frames","Enter the number of frames"
parm=0,"Frame width","Enter the frame width in degrees 2theta"
parm=0,"Theta1","Enter the initial Theta1 (degrees)"
parm=0,"Theta2","Enter the initial Theta2 (degrees)"

[12]
menu="&Monochrome Printing"
help="Print screen in Black/White only"
slam="@GADDS$TEST:printblk"
